GOOGLE_CLIENT_ID = "88466204547-8b1dbbaoa5u1i2nsso92mjmiubnfn9do.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
​Opsional: Jika ingin memindahkan isi JSON Firebase ke sini
​FIREBASE_SECRET = '{"type": "service_account", ...}'
